module Infer where

import Common

import Control.Monad.Writer (listen)
import Control.Monad.Except (throwError)
import Data.Map.Strict as H (Map, insert, lookup, empty, fromList, singleton)

tag1 = 64002
tag2 = 68869
tag3 = 19545

  {- question 1: fresh instance function -}

freshInst :: PolyTy -> Infer MonoTy
freshInst (Forall qVars tau) = 
  do 
--     freshTau :: Infer MonoTy
-- freshTau = TyVar <$> fresh
-- data PolyTy = Forall [VarId] MonoTy
--for each qvar in array, get a freshvariable
    freshVars <- mapM (\x -> freshTau) qVars 
    let subst = H.fromList (zip qVars freshVars)
    return ( apply subst tau)
  

  {- question 2: occurs check -}

occurs :: VarId -> MonoTy -> Bool
occurs i tau = case tau of 
  (TyVar varid) -> (varid == i) 
  (TyConst s []) -> False 
  (TyConst s (x:xs)) -> occurs i x || occurs i (TyConst s xs)


  {- question 3: unification -}

unify :: [Constraint] -> Infer Substitution
unify [] = return substEmpty
unify (x:xs) = case x of 
  (t1 :~: t2 ) -> case (t1, t2) of 
    -- DELETE
    (TyVar s, TyVar t) | s == t -> unify xs
    -- ELIMINATE
    (TyVar s, t2)
      | occurs s t2 -> throwError (InfiniteType s t2)  -- eliminate rule substitute all occurences of s in φ′with t to get φ′′. Let σ be the substitution resulting from unifying φ′′. Return σ updated with s 7→σ(t)

      | otherwise -> do
        let sub = substInit s t2
        let phi = map (apply sub) xs 
        sigma <- unify phi 
        return (substCompose sigma sub)
        
        --ORIENT
    (s, TyVar tau) -> unify ((TyVar tau :~: s):xs)

    (TyConst c1 v1, TyConst c2 v2) 
      | c1 == c2 -> unify ((zipWith (:~:) v1 v2) ++ xs)
      | otherwise -> throwError (Can'tMatch t1 t2)

  {- question 4: type inference -}


-- 1. Let Γ = {}.
-- 2. We examine fun x -> x + 2 and see that it is a fun. We don’t know what x will be, so we let it have type 'a. Add that to
-- Γ and try to infer the type of the body . . .
-- (a) Examine x + 2. We apply the above rule, so we need to infer the subtypes.
-- i. Examine x. Γ says that x has type 'a.
-- ii. Examine 2. This is an int.
-- (b) We return that the type of the body is int, along with the constraint set {'a ∼int,int ∼int}. Yes, the last constraint
-- is trivial, but the rule says we have to do it. Note that in code, we don’t need to manually combine the new constraints with
-- φ1 and φ2, because the monad is handling that for us. The new constraints would be generated by two calls to constrain.
-- 3. Now we’re ready to come back to the type of the whole expression. The variable x has type 'a, and the output has type int, so
-- the whole expression has type 'a -> int, subject to the constraint set {'a ∼int,int ∼int}.
-- 4. Unify the constraint set to find the substitution that solves it; the substitution is {'a 7→int}.
-- 5. The substitution tells us that we need to rewrite 'a to int everywhere, so we get a final type of int -> int



infer :: TypeEnv -> Exp -> Infer MonoTy
-- constants
-- Note that this makes use of both the freshInst and constTySig auxiliary functions. Remember that freshInst returns its
-- result in the monad.
-- A sample execution would be
-- Enter an expression:
-- 46
-- Parsed as:
-- 46
-- Inferred type:
-- int
infer env (ConstExp c) = freshInst (constTySig c)

-- variables
infer env (VarExp s) = case (H.lookup s env) of 
  (Just polytype) -> freshInst polytype
  Nothing -> throwError (LookupError s)

-- LetInExp 
infer env (LetExp x e1 e2) = do
  --   After inferring the type of y, it will be a type variable 'a and we will have a constraint 'a ∼ int. 
  (t1, phi1) <- listen (infer env e1)

-- We would then apply GEN immediately, adding [y : ∀′a.′a] to Γ while typechecking e. 
-- we have to unify the constraints generated by inferring the type of e1 and apply the resulting substitution to τ1 before
-- generalizing it
  sub <- unify phi1
  let t1' = apply sub t1
  let generalized = gen env t1'

  let env' = H.insert x generalized env

--Then, while typechecking e, we call freshInst on the type of y and we return
  t2 <- infer env' e2

  return t2

-- Unary
infer env (MonOpExp m e') = do
  t1 <- (infer env e')
  freshvariable <- freshTau

  binder <- freshInst (monopTySig m)

  constrain (funTy t1 freshvariable) binder

  return freshvariable

-- Binary  
infer env (BinOpExp b e1 e2) = do
  t1 <- (infer env e1)
  t2 <- (infer env e2)

  freshvariable <- freshTau

  binder <- freshInst (binopTySig b)

  constrain (funTy t1 (funTy t2 freshvariable)) binder

  return freshvariable

-- if then else
infer env (IfExp e1 e2 e3) = undefined

-- function
infer env (FunExp x e') = undefined
  

-- application
infer env (AppExp e1 e2) = undefined

-- LetRecInExp
infer env (LetRecExp f x e1 e2) = undefined


inferInit :: TypeEnv -> Exp -> Infer PolyTy
inferInit env e = do
  (tau, constraints) <- listen $ infer env e
  substitution <- unify constraints
  return $ quantifyMonoTy $ apply substitution tau

inferDec :: TypeEnv -> Dec -> Infer (TypeEnv, PolyTy)
inferDec env (AnonDec e') = do
  tau <- inferInit env e'
  return (env, tau)
inferDec env (LetDec x e') = do
  tau <- inferInit env (LetExp x e' (VarExp x))
  return (H.insert x tau env, tau)
inferDec env (LetRec f x e') = do
  tau <- inferInit env (LetRecExp f x e' (VarExp f))
  return (H.insert f tau env, tau)
